### ISSUE TITLE
Remove or fix old broken tests

### ISSUE THREAD

**Issue by Mackiovello** [StarcounterApps/Products#42]
The tests are broken since a while back and should be either removed or fixed. I suggest removing them so that the tests are consistent across the sample apps.

```
C:\Users\Erlend\Documents\apps\Products>npm test

> products@4.0.0 test C:\Users\Erlend\Documents\apps\Products
> mocha



  Products app
    1) Get cookie
    2) Verify cookie
    3) Set product name
    4) Get added product


  0 passing (787ms)
  4 failing

  1) Products app Get cookie:
     Error: expected "set-cookie" header field
      at Test.assert (C:\Users\Erlend\Documents\apps\Products\node_modules\supertest\lib\test.js:190:35)
      at assert (C:\Users\Erlend\Documents\apps\Products\node_modules\supertest\lib\test.js:132:12)
      at C:\Users\Erlend\Documents\apps\Products\node_modules\supertest\lib\test.js:129:5
      at Test.Request.callback (C:\Users\Erlend\Documents\apps\Products\node_modules\superagent\lib\node\index.js:746:30)
      at Test.<anonymous> (C:\Users\Erlend\Documents\apps\Products\node_modules\superagent\lib\node\index.js:135:10)
      at IncomingMessage.<anonymous> (C:\Users\Erlend\Documents\apps\Products\node_modules\superagent\lib\node\index.js:938:12)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  2) Products app Verify cookie:
     Error: "value" required in setHeader("X-Referer", value)
      at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:354:11)
      at Test.Request.set (C:\Users\Erlend\Documents\apps\Products\node_modules\superagent\lib\node\index.js:275:18)
      at Context.<anonymous> (C:\Users\Erlend\Documents\apps\Products\test\test.js:29:10)
      at callFnAsync (C:\Users\Erlend\Documents\apps\Products\node_modules\mocha\lib\runnable.js:349:8)
      at Test.Runnable.run (C:\Users\Erlend\Documents\apps\Products\node_modules\mocha\lib\runnable.js:301:7)
      at Runner.runTest (C:\Users\Erlend\Documents\apps\Products\node_modules\mocha\lib\runner.js:422:10)
      at C:\Users\Erlend\Documents\apps\Products\node_modules\mocha\lib\runner.js:528:12
      at next (C:\Users\Erlend\Documents\apps\Products\node_modules\mocha\lib\runner.js:342:14)
      at C:\Users\Erlend\Documents\apps\Products\node_modules\mocha\lib\runner.js:352:7
      at next (C:\Users\Erlend\Documents\apps\Products\node_modules\mocha\lib\runner.js:284:14)
      at Immediate.<anonymous> (C:\Users\Erlend\Documents\apps\Products\node_modules\mocha\lib\runner.js:320:5)

  3) Products app Set product name:
     TypeError: undefined
      at urlFormat (url.js:552:11)
      at Test.Request (C:\Users\Erlend\Documents\apps\Products\node_modules\superagent\lib\node\index.js:121:37)
      at new Test (C:\Users\Erlend\Documents\apps\Products\node_modules\supertest\lib\test.js:29:11)
      at Object.obj.(anonymous function) [as patch] (C:\Users\Erlend\Documents\apps\Products\node_modules\supertest\index.js:25:14)
      at Context.<anonymous> (C:\Users\Erlend\Documents\apps\Products\test\test.js:42:10)
      at callFnAsync (C:\Users\Erlend\Documents\apps\Products\node_modules\mocha\lib\runnable.js:349:8)
      at Test.Runnable.run (C:\Users\Erlend\Documents\apps\Products\node_modules\mocha\lib\runnable.js:301:7)
      at Runner.runTest (C:\Users\Erlend\Documents\apps\Products\node_modules\mocha\lib\runner.js:422:10)
      at C:\Users\Erlend\Documents\apps\Products\node_modules\mocha\lib\runner.js:528:12
      at next (C:\Users\Erlend\Documents\apps\Products\node_modules\mocha\lib\runner.js:342:14)
      at C:\Users\Erlend\Documents\apps\Products\node_modules\mocha\lib\runner.js:352:7
      at next (C:\Users\Erlend\Documents\apps\Products\node_modules\mocha\lib\runner.js:284:14)
      at Immediate.<anonymous> (C:\Users\Erlend\Documents\apps\Products\node_modules\mocha\lib\runner.js:320:5)

  4) Products app Get added product:
     Error: "value" required in setHeader("X-Referer", value)
      at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:354:11)
      at Test.Request.set (C:\Users\Erlend\Documents\apps\Products\node_modules\superagent\lib\node\index.js:275:18)
      at Context.<anonymous> (C:\Users\Erlend\Documents\apps\Products\test\test.js:53:10)
      at callFnAsync (C:\Users\Erlend\Documents\apps\Products\node_modules\mocha\lib\runnable.js:349:8)
      at Test.Runnable.run (C:\Users\Erlend\Documents\apps\Products\node_modules\mocha\lib\runnable.js:301:7)
      at Runner.runTest (C:\Users\Erlend\Documents\apps\Products\node_modules\mocha\lib\runner.js:422:10)
      at C:\Users\Erlend\Documents\apps\Products\node_modules\mocha\lib\runner.js:528:12
      at next (C:\Users\Erlend\Documents\apps\Products\node_modules\mocha\lib\runner.js:342:14)
      at C:\Users\Erlend\Documents\apps\Products\node_modules\mocha\lib\runner.js:352:7
      at next (C:\Users\Erlend\Documents\apps\Products\node_modules\mocha\lib\runner.js:284:14)
      at Immediate.<anonymous> (C:\Users\Erlend\Documents\apps\Products\node_modules\mocha\lib\runner.js:320:5)



npm ERR! Test failed.  See above for more details.
```

**Comment by warpech** [comment]
I agree that they should be removed.

**Comment by Mackiovello** [comment]
Done in 	5f6f2e6
